import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';
/* 
  Algoritmo qye solicite n cantidad de numeros, una vez los haya solicitado, 
  los valores deben ser almacenados en una estructura de datos cola.
  Posteriormente, se debe buscar el promedio de los numeros ingresados.

  1. Solicitar n cantidad de numeros
  2. Almacenar los numeros en una estructura de datos cola
  3. Buscar el promedio de los numeros ingresados
*/

export default function Home() {

  //Input para ingresar un número que sea el tamaño del array
  const [numero, setNumero] = useState(0); //Tamaño del array, Línea 18:1 operación de declaración y asignación de variable de estado.
  //Cola
  const [cola, setCola] = useState<number[]>([]); //Cola, Línea 23: 1 operaciones de declaración y asignación de variables de estado.//
  // Promedio
  const [promedios, setPromedios] = useState(0); //Promedio, Línea 26: 1 operaciones de declaración y asignación de variables de estado.//


  //1. Crear un input para ingresar un número que sea el tamaño del array
  const handleChange = (e:any) => {
    setNumero(Number(e.target.value)); //Línea 30: 1 operación de asignación de variable de estado.
  };
  
  //2. Almacernar los numeros en una estructura de datos cola
  class Queue<T> {
    public elements: T[] = [];
  
    enqueue(element: T): void {
      this.elements.push(element);
    }
  
    dequeue(): T | undefined {
      return this.elements.shift();
    }
  
    isEmpty(): boolean {
      return this.elements.length === 0;
    }
  }
  
  //3. Buscar el promedio de los numeros ingresados
  const promedio = (cola: number[]) => {
    let suma = 0;
    for (let i = 0; i < cola.length; i++) {
      suma += cola[i];
    }
    return suma / cola.length;
  };

  //2. Crear un botón que al hacer click genere un array con numeros con el tamaño del input anterior
  const handleClick = () => {
    const queue = new Queue<number>();
    for (let i = 0; i < numero; i++) {
      const numero = Number(prompt(`Ingrese el numero ${i + 1}`));
      queue.enqueue(numero);
    }
    setCola(queue.elements); //Línea 68: 1 operación de asignación de variable de estado.
    setPromedios(promedio(queue.elements)); //Línea 69: 1 operación de asignación de variable de estado.
  };

  //4. Imprimir la cola en pantalla
  const imprimirCola = () => {
    return cola.map((numero, index) => {
      return <li key={index}>{numero}</li>;
    });
  };

  return (
    <>
    <Head>
      <title>Estructura de datos cola numeros agregados a una cola y buscamos su promedio</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <div className={styles.description}>
        <p>
          Para ver el codigo del programa&nbsp;
          <code className={styles.code}>src/pages/index.tsx</code>
        </p>
      </div>

      <div className={styles.main}>
        <h1 className={styles.h1}>
          Algoritmo numeros agregados a una cola y buscamos su promedio
        </h1>
        <p className={styles.p}>
          El usuario determina el tamaño del arreglo y el programa genera una
          ventana emergente para que el usuario ingrese los numeros hasta
          llenar el array en la cola con el tamaño ingresado. Una vez lleno el arreglo,
          el programa saca el promedio de los numeros ingresados.
        </p>
        {/* 1.Crear un input para ingresar un número que sea el tamaño del array */}
        {/* Tamaño del arreglo: */}
        <label htmlFor="numero" className={styles.h1}>Tamaño del arreglo:</label>
        <input
          type="number"
          name="numero"
          id="numero"
          className={styles.input}
          onChange={handleChange}
        />
        <p className={styles.p}>
          Cuando ingrese el tamaño ejecute el boton generar el arreglo este
          desplega una ventana emergente para llenar el tamaño del arreglo con
          los numeros que le ingreses.
        </p>
        {/* 2.Crear un botón que al hacer click genere un array con numeros con el tamaño del input anterior */}
        <button onClick={handleClick} className={styles.button}>Generar array</button>
        {/* 3.el promedio de los numeros ingresados */}
        <p className={styles.p}>El promedio de los numeros ingresados es:{promedios}</p>
        {/* 4. Imprimir la cola en pantalla */}
        <ul className={styles.ul}>{imprimirCola()}</ul>
      </div>
    </main>
  </>
  )
}
